<?php
$_helper = Mage::helper("advancedcatalog");
$_filterMode = $_helper->getConfig("filter_mode", "list");
?>
<?php if ($this->canShowBlock()): ?>
    <div class="block block-layered-nav">
        <div class="block-title">
            <strong><span><?php echo $this->__('Shop By') ?></span></strong>
        </div>
        <div class="block-content">
            <?php echo $this->getStateHtml() ?>
            <?php if ($this->getLayer()->getState()->getFilters()): ?>
                <div class="actions"><a
                            href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
            <?php endif; ?>
            <?php if ($this->canShowOptions()): ?>
                <p class="block-subtitle"><?php echo $this->__('Shopping Options') ?></p>
                <dl id="narrow-by-list">
                    <?php $_filters = $this->getFilters() ?>
                    <?php $_filterCount = 1 ?>
                    <?php foreach ($_filters as $_filter): ?>
                        <?php if ($_filter->getItemsCount()): ?>
                            <?php if ($_filterMode == "accordion"): ?>
                                <dt id="accordion-filter_<?php echo $_filterCount?>" class="card" data-toggle="collapse"
                                    data-target="#collapse-filter_<?php echo $_filterCount?>" aria-expanded="true"
                                    aria-controls="collapse-filter_<?php echo $_filterCount?>"><?php echo $this->__($_filter->getName()) ?></dt>
                                <dd id="collapse-filter_<?php echo $_filterCount?>" class="collapse show"
                                     data-parent="#accordion-filter_<?php echo $_filterCount?>">
                                    <?php echo $_filter->getHtml() ?>
                                </dd>
                            <?php else: ?>
                                <dt><?php echo $this->__($_filter->getName()) ?></dt>
                                <dd><?php echo $_filter->getHtml() ?></dd>
                            <?php endif; $_filterCount++?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dl>
                <script type="text/javascript">decorateDataList('narrow-by-list')</script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
